#!/bin/sh
# Regenerates src/fuddy_duddy/syscalls_x86_64.py from the kernel headers.
# Run inside the dev shell:  sh collector/gen-syscall-table.sh
set -eu
cd "$(dirname "$0")/.."
out=src/fuddy_duddy/syscalls_x86_64.py
{
    echo '"""x86_64 syscall number -> name table.'
    echo
    echo 'Generated by collector/gen-syscall-table.sh; do not edit by hand.'
    echo '"""'
    echo
    echo 'NAMES: dict[int, str] = {'
    echo '#include <asm/unistd_64.h>' | gcc -E -dM - |
        sed -n 's/^#define __NR_\([a-z0-9_]*\) \([0-9]*\)$/\2 \1/p' |
        sort -n |
        sed 's/^\([0-9]*\) \(.*\)$/    \1: "\2",/'
    echo '}'
    echo
    echo 'NR: dict[str, int] = {name: nr for nr, name in NAMES.items()}'
} > "$out"
echo "wrote $out"
